<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="PRG_TXI_VAC" Id="{80e6a8be-3822-46f9-baac-97367240f381}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TXI_VAC
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// MSK275 Gauges
fb_ST1L1_GPI_01(PG=>);

// MSK 500 Gauges
fb_ST1L1_GCC_01(PG := fb_ST1L1_GPI_01.PG, bEP := TRUE);]]></ST>
    </Implementation>
    <LineIds Name="PRG_TXI_VAC">
      <LineId Id="13" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>