<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="PRG_TXI_VAC_VALVES" Id="{e927dcd4-ebf1-4ef3-837f-3b457a096b9c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TXI_VAC_VALVES
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_TXI_VAC_VALVES">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>